site_name: The Notebook
site_url: https://meyerv11045.github.com/notes
docs_dir: notes

nav:
  - Basics:
    - 'Software Engineering Notebook': 'general/swe-notes.md'
    - 'Git': 'general/git.md'
    - 'Python': 'general/python.md'
    - 'MacOS': 'general/macos.md'
    - 'Programming Paradigms': 'general/paradigms.md'
    - 'Regex': 'general/regex.md'
    - 'Hardware': 'general/hardware.md'
  - Data Structures:
    - 'Linked List': 'data_structures/linked-list.md'
    - 'Stack': 'data_structures/stack.md'
    - 'Queue': 'data_structures/queue.md'
    - 'Tree': 'data_structures/tree.md'
    - 'Graph': 'data_structures/graph.md'
    - 'Hash Table': 'data_structures/hash-table.md'
    - 'Heap': 'data_structures/heap.md'
  - Software Design:
    - 'Pointers': 'software_design/pointers.md'
    - 'The Big 3': 'software_design/big3.md'
    - 'Misc': 'software_design/misc.md'
  - Databases:
    - "DBMS": 'databases/dbms.md'
    - 'SQL': 'databases/sql.md'
    - 'MySQL': 'databases/mysql.md'
  - System Design:
    - 'Microservices': 'system_design/microservices.md'
    - 'Docker': 'system_design/docker.md'
  - Web Development:
    - Javascript:
      - 'Basics': 'web_dev/js/basics.md'
      - 'Classes': 'web_dev/js/classes.md'
      - 'Objects': 'web_dev/js/objects.md'
      - 'Modules': 'web_dev/js/modules.md'
      - 'Promises': 'web_dev/js/promises.md'
      - 'jQuery': 'web_dev/js/jQuery.md'
      - 'Node Pkgs': 'web_dev/js/using_node_pkgs.md'
      - 'Browser Compatibility': 'web_dev/js/browser_compatibility.md'
    - HTML & CSS:
      - 'Sass': 'web_dev/html-css/sass.md'