site_name: Personal Notes
site_url: https://meyerv11045.github.com/notes
docs_dir: notes

nav:
  - Basics:
    - 'Software Engineering Notebook': 'basics/swe-notes.md'
    - 'Programming Paradigms': 'basics/paradigms.md'
    - 'Object Oriented Programming': 'basics/oop.md'
    - 'Regex': 'basics/regex.md'
    - 'Terminal Commands': 'basics/terminal-cmds.md'
  - Data Structures:
    - 'Linked List': 'data_structures/linked-list.md'
    - 'Stack': 'data_structures/stack.md'
    - 'Queue': 'data_structures/queue.md'
    - 'Tree': 'data_structures/tree.md'
    - 'Graph': 'data_structures/graph.md'
    - 'Hash Table': 'data_structures/hash-table.md'
    - 'Heap': 'data_structures/heap.md'
  - Databases:
    - "DBMS": 'databases/dbms.md'
    - 'SQL': 'databases/sql.md'
  - System Design:
    - 'Microservices': 'system_design/microservices.md'
    - 'Docker': 'system_design/overview.md'
  - Web Development:
    - Javascript:
      - 'Basics': 'web_dev/js/basics.md'
      - 'Classes': 'web_dev/js/classes.md'
      - 'Objects': 'web_dev/js/objects.md'
      - 'Modules': 'web_dev/js/modules.md'
      - 'Promises': 'web_dev/js/promises.md'
      - 'jQuery': 'web_dev/js/jQuery.md'
      - 'Node Pkgs': 'web_dev/js/using_node_pkgs.md'
      - 'Browser Compatibility': 'web_dev/js/browser_compatibility.md'
    - HTML & CSS:
      - 'Sass': 'web_dev/html-css/sass.md'
  - Machine Learning:
    - 'Reinforcement Learning': 'machine_learning/reinforcement_learning.md'
    - 'Activation Functions': 'machine_learning/activation_functions.md'
  - Hardware:
    - '3D Printing': 'hardware/3d-printing.md'
    - 'Raspberry Pi': 'hardware/raspberry-pi.md'