site_name: The Notebook
site_url: https://meyerv11045.github.com/notes
docs_dir: notes

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

nav:
  - Python:
    - 'Overview': 'python/overview.md'
    - 'Style': 'python/style.md'
    - 'Types': 'python/types.md'
    - 'Concurrency': 'python/concurrency.md'
    - 'Dunder Methods': 'python/dunders.md'
  - SWE:
    - 'Software Engineering Notebook': 'swe/swe-notes.md'
    - 'Git': 'swe/git.md'
    - 'Terminal Cmds': 'swe/terminal-cmds.md'
    - 'Microservices': 'swe/microservices.md'
    - 'Docker': 'swe/docker.md'
    - 'Regex': 'swe/regex.md'
  - Multimedia:
    - 'Overview': 'multimedia/overview.md'
    - 'Streaming': 'multimedia/streaming.md'
  - Azure:
    - Storage:
      - 'Overview': 'azure/storage/overview.md'
      - 'Blobs': 'azure/storage/blob_storage.md'
    - Networking:
      - 'Virtual Networks': 'cloud/networking/vnets.md'
  - Algorithms:
    - Graphs:
      - 'Representations': 'algorithms/graphs/graphs.md'
      - 'BFS & DFS': 'algorithms/graphs/bfs_dfs.md'
      - 'Undirected': 'algorithms/graphs/undirected.md'
      - 'Directed': 'algorithms/graphs/directed.md'
      - 'Network Flow': 'algorithms/graphs/max_flow.md'
    - 'Analysis': 'algorithms/analysis.md'
    - 'Sorting': 'algorithms/sorting.md'
    - 'Heaps': 'algorithms/heaps.md'
    - 'Greedy': 'algorithms/greedy.md'
    - 'Dynamic Programming': 'algorithms/dp.md'
    - 'Divide and Conquer': 'algorithms/divideconquer.md'
    - 'Tips': 'algorithms/tips.md'
    - 'Complexity Theory': 'algorithms/complexity.md'
  - Data Structures:
    - 'Overview': 'data_structures/overview.md'
    - 'Linked List': 'data_structures/linked-list.md'
    - 'Stack': 'data_structures/stack.md'
    - 'Queue': 'data_structures/queue.md'
    - 'Heap': 'data_structures/heap.md'
    - 'Graph': 'data_structures/graph.md'
  - Software Design:
    - C++:
      - 'Cmake': 'software_design/cpp/cmake.md'
      - 'Pointers': 'software_design/cpp/pointers.md'
      - 'The Big 3': 'software_design/cpp/big3.md'
      - 'Exception Handling': 'software_design/cpp/exceptions.md'
      - 'Templates': 'software_design/cpp/templates.md'
      - 'Operator Overloading': 'software_design/cpp/operator-overloading.md'
      - 'Strong Exception Safety': 'software_design/cpp/strong-exception-safety.md'
      - 'Smart Pointers': 'software_design/cpp/smart-pointers.md'
      - 'Inheritance': 'software_design/cpp/inheritance.md'
      - 'Iterators': 'software_design/cpp/iterators.md'
      - 'STL': 'software_design/cpp/stl.md'
      - 'Functors': 'software_design/cpp/functors.md'
      - 'Lambda Functions': 'software_design/cpp/lambda.md'
      - 'Misc': 'software_design/cpp/misc.md'
    - Patterns:
      - 'Overview': 'software_design/patterns/patterns.md'
      - 'Adapter': 'software_design/patterns/adapter.md'
      - 'Observer': 'software_design/patterns/observer.md'
      - 'Singleton': 'software_design/patterns/singleton.md'
      - 'Composite': 'software_design/patterns/composite.md'
      - 'Interpreter': 'software_design/patterns/interpreter.md'
      - 'Builder': 'software_design/patterns/builder.md'
      - 'Visitor': 'software_design/patterns/visitor.md'
      - 'Iterator': 'software_design/patterns/iterator.md'
      - 'Bridge': 'software_design/patterns/bridge.md'
      - 'Command': 'software_design/patterns/command.md'
      - 'Factory': 'software_design/patterns/factory.md'
      - 'State': 'software_design/patterns/state.md'
      - 'Reactor': 'software_design/patterns/reactor.md'
      - 'Strategy': 'software_design/patterns/strategy.md'
      - 'Template': 'software_design/patterns/template.md'
  - Programming Languages:
    - 'Programming Paradigms': 'prog_langs/paradigms.md'
    - 'Ch. 1 Introduction': 'prog_langs/ch1.md'
    - 'Ch. 2 History': 'prog_langs/ch2.md'
    - 'Ch. 3 Syntax & Semantics': 'prog_langs/ch3.md'
    - 'Ch. 5 Names, Bindings, & Scope': 'prog_langs/ch5.md'
    - 'Ch. 6 Data Types': 'prog_langs/ch6.md'
    - 'Ch. 7 Expression': 'prog_langs/ch7.md'
    - 'Ch. 15 Functional Languages: Racket': 'prog_langs/ch15.md'
    - 'Ch. 16 Logical Languages: Prolog': 'prog_langs/ch16.md'
  - Robotics:
    - 'Control': 'robotics/control.md'
    - 'Behavior Trees': 'robotics/behavior-trees.md'
    - 'Hardware': 'robotics/hardware.md'
  - Digital Systems:
    - 'Assembly': 'dig_sys/ch6-assembly.md'
    - 'Microarchitecture': 'dig_sys/ch7-processor.md'
    - 'Memory Systems': 'dig_sys/ch8-mem-sys.md'
    - 'IO Systems': 'dig_sys/ch9-io-sys.md'
  - Prob & Stats:
    - 'Random Variables': 'math_science/prob_stats/rv.md'
    - 'Continuous Random Variables': 'math_science/prob_stats/crvs.md'
    - 'Joint Probability Distributions': 'math_science/prob_stats/joint-distributions.md'
    - 'Statistics': 'math_science/prob_stats/stats.md'
  - Science:
    - 'The Brain': 'math_science/brain.md'
    - 'Molecular Genetics': 'math_science/molecular_genetics.md'
    - 'Dev Psychology': 'math_science/dev_psy.md'
    - 'Current & Resistance': 'math_science/physics/ch25.md'
  - Web Dev:
    - Javascript:
      - 'Basics': 'web_dev/js/basics.md'
      - 'Classes': 'web_dev/js/classes.md'
      - 'Objects': 'web_dev/js/objects.md'
      - 'Modules': 'web_dev/js/modules.md'
      - 'Promises': 'web_dev/js/promises.md'
      - 'jQuery': 'web_dev/js/jQuery.md'
      - 'Node Pkgs': 'web_dev/js/using_node_pkgs.md'
      - 'Browser Compatibility': 'web_dev/js/browser_compatibility.md'
    - HTML & CSS:
      - 'Sass': 'web_dev/html-css/sass.md'
    - Databases:
      - "DBMS": 'databases/dbms.md'
      - 'SQL': 'databases/sql.md'
      - 'MySQL': 'databases/mysql.md'
  - Misc:
    - 'MacOS': 'misc/macos.md'
    - 'How to Speak': 'misc/how-to-speak.md'