site_name: The Notebook
site_url: https://meyerv11045.github.com/notes
docs_dir: notes

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

nav:
  - General:
    - 'Software Engineering Notebook': 'general/swe-notes.md'
    - 'Git': 'general/git.md'
    - 'Python': 'general/python.md'
    - 'MacOS': 'general/macos.md'
    - 'Programming Paradigms': 'general/paradigms.md'
    - 'Regex': 'general/regex.md'
    - 'Hardware': 'general/hardware.md'
    - 'Microservices': 'system_design/microservices.md'
    - 'Docker': 'system_design/docker.md'
  - Data Structures:
    - 'Overview': 'data_structures/overview.md'
    - 'Linked List': 'data_structures/linked-list.md'
    - 'Stack': 'data_structures/stack.md'
    - 'Queue': 'data_structures/queue.md'
    - 'Heap': 'data_structures/heap.md'
  - Software Design:
    - C++:
      - 'Pointers': 'software_design/cpp/pointers.md'
      - 'The Big 3': 'software_design/cpp/big3.md'
      - 'Exception Handling': 'software_design/cpp/exceptions.md'
      - 'Templates': 'software_design/cpp/templates.md'
      - 'Operator Overloading': 'software_design/cpp/operator-overloading.md'
      - 'Strong Exception Safety': 'software_design/cpp/strong-exception-safety.md'
      - 'Smart Pointers': 'software_design/cpp/smart-pointers.md'
      - 'Inheritance': 'software_design/cpp/inheritance.md'
      - 'Iterators': 'software_design/cpp/iterators.md'
      - 'STL': 'software_design/cpp/stl.md'
      - 'Functors': 'software_design/cpp/functors.md'
      - 'Lambda Functions': 'software_design/cpp/lambda.md'
      - 'Misc': 'software_design/cpp/misc.md'
    - Patterns:
      - 'Overview': 'software_design/patterns/patterns.md'
      - 'Adapter': 'software_design/patterns/adapter.md'
  - Databases:
    - "DBMS": 'databases/dbms.md'
    - 'SQL': 'databases/sql.md'
    - 'MySQL': 'databases/mysql.md'
  - Web Dev:
    - Javascript:
      - 'Basics': 'web_dev/js/basics.md'
      - 'Classes': 'web_dev/js/classes.md'
      - 'Objects': 'web_dev/js/objects.md'
      - 'Modules': 'web_dev/js/modules.md'
      - 'Promises': 'web_dev/js/promises.md'
      - 'jQuery': 'web_dev/js/jQuery.md'
      - 'Node Pkgs': 'web_dev/js/using_node_pkgs.md'
      - 'Browser Compatibility': 'web_dev/js/browser_compatibility.md'
    - HTML & CSS:
      - 'Sass': 'web_dev/html-css/sass.md'
  - Math & Science:
    - 'The Brain': 'math_science/brain.md'
    - Physics: 
      - 'Current & Resistance': 'math_science/physics/ch25.md'
    - Prob & Stats:
      - 'Random Variables': 'math_science/prob_stats/rv.md'
      - 'Continuous Random Variables': 'math_science/prob_stats/crvs.md'
      - 'Joint Probability Distributions': 'math_science/prob_stats/joint-distributions.md'